init:
  - git config --global core.autocrlf true
build_script:
  - build.cmd --quiet verify
clone_depth: 1
test: off
deploy: off
environment:
  NO_PARALLEL_TEST_PROJECTS: Microsoft.AspNet.Server.Kestrel.FunctionalTests